import{a as w,S,i as a}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const E="https://pixabay.com/api/",P="53360647-c263b6c497f5f63021bb419c5",v=15;async function u(n,o){const e={key:P,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:v,page:o};return(await w.get(E,{params:e})).data}const d=document.querySelector(".gallery"),f=document.querySelector(".loader"),p=document.querySelector(".load-more-btn"),q=new S(".gallery a",{captionData:"alt",captionDelay:250});function h(n){const o=n.map(e=>`
                <li class="gallery-item">
                    <a href="${e.largeImageURL}">
                        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
                    </a>
                    <div class="info">
                     <p><b>Likes </b>${e.likes}</p>
                     <p><b>Views </b>${e.views}</p>
                     <p><b>Comments </b>${e.comments}</p>
                     <p><b>Downloads </b>${e.downloads}</p>
                    </div>
                </li>`).join("");d.insertAdjacentHTML("beforeend",o),q.refresh()}function M(){d.innerHTML=""}function m(){f.classList.remove("hidden")}function g(){f.classList.add("hidden")}function y(){p.classList.remove("hidden")}function l(){p.classList.add("hidden")}const R=document.querySelector(".form"),O=document.querySelector('input[name="search-text"]'),$=document.querySelector(".load-more-btn");let i=1,b="";const L=15;R.addEventListener("submit",A);$.addEventListener("click",B);function A(n){n.preventDefault();const o=O.value.trim();if(!o){a.error({title:"Error",message:"Search field cannot be empty!",position:"topRight"});return}i=1,b=o,M(),m(),l(),u(o,i).then(e=>{if(e.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(e.hits);const s=Math.ceil(e.totalHits/L);i<s&&y()}).catch(e=>{console.error(e),a.error({title:"Error",message:"Something went wrong!",position:"topRight"})}).finally(()=>{g()})}function B(){i++,m(),l(),u(b,i).then(n=>{h(n.hits);const o=Math.ceil(n.totalHits/L);i>=o?(a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l()):y()}).catch(()=>{a.error({title:"Error",message:"Something went wrong! while loading more images!",position:"topRight"})}).finally(()=>{g()})}
//# sourceMappingURL=index.js.map
