import{a as w,S,i as a}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=e(t);fetch(t.href,n)}})();const v="https://pixabay.com/api/",E="53360647-c263b6c497f5f63021bb419c5",P=15;async function d(r,o){const e={key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:o};return(await w.get(v,{params:e})).data}const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),q=new S(".gallery a",{captionData:"alt",captionDelay:250});function p(r){const o=r.map(e=>`
                <li class="gallery-item">
                    <a href="${e.largeImageURL}">
                        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
                    </a>
                    <div class="info">
                     <p><b>Likes </b>${e.likes}</p>
                     <p><b>Views </b>${e.views}</p>
                     <p><b>Comments </b>${e.comments}</p>
                     <p><b>Downloads </b>${e.downloads}</p>
                    </div>
                </li>`).join("");u.insertAdjacentHTML("beforeend",o),q.refresh()}function R(){u.innerHTML=""}function m(){f.classList.remove("hidden")}function y(){f.classList.add("hidden")}function g(){h.classList.remove("hidden")}function l(){h.classList.add("hidden")}const M=document.querySelector(".form"),B=document.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more-btn");let i=1,b="";const L=15;M.addEventListener("submit",$);O.addEventListener("click",A);async function $(r){r.preventDefault();const o=B.value.trim();if(!o){a.error({title:"Error",message:"Search field cannot be empty!",position:"topRight"});return}i=1,b=o,R(),m(),l();try{const e=await d(o,i);if(!e.hits.length){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(e.hits);const s=Math.ceil(e.totalHits/L);i<s&&g()}catch(e){console.error(e),a.error({title:"Error",message:"Something went wrong!",position:"topRight"})}finally{y()}}async function A(){i++,m(),l();try{const r=await d(b,i);p(r.hits);const o=document.querySelector(".gallery li");if(o){const{height:s}=o.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}const e=Math.ceil(r.totalHits/L);i>=e?(a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l()):g()}catch(r){console.error(r),a.error({title:"Error",message:"Something went wrong! while loading more images!",position:"topRight"})}finally{y()}}
//# sourceMappingURL=index.js.map
