import{a as w,S,i as s}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const v="https://pixabay.com/api/",E="53360647-c263b6c497f5f63021bb419c5",P=15;async function d(n,o){const e={key:E,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:o};return(await w.get(v,{params:e})).data}const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),q=new S(".gallery a",{captionData:"alt",captionDelay:250});function p(n){const o=n.map(e=>`
                <li class="gallery-item">
                    <a href="${e.largeImageURL}">
                        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
                    </a>
                    <div class="info">
                     <p><b>Likes </b>${e.likes}</p>
                     <p><b>Views </b>${e.views}</p>
                     <p><b>Comments </b>${e.comments}</p>
                     <p><b>Downloads </b>${e.downloads}</p>
                    </div>
                </li>`).join("");u.insertAdjacentHTML("beforeend",o),q.refresh()}function R(){u.innerHTML=""}function m(){f.classList.remove("hidden")}function y(){f.classList.add("hidden")}function g(){h.classList.remove("hidden")}function l(){h.classList.add("hidden")}const M=document.querySelector(".form"),B=document.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more-btn");let a=1,b="";const L=15;M.addEventListener("submit",$);O.addEventListener("click",A);async function $(n){n.preventDefault();const o=B.value.trim();if(!o){s.error({title:"Error",message:"Search field cannot be empty!",position:"topRight"});return}a=1,b=o,R(),m(),l();try{const e=await d(o,a);if(e.hits.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(e.hits);const i=Math.ceil(e.totalHits/L);a<i&&g()}catch{s.error({title:"Error",message:"Something went wrong!",position:"topRight"})}finally{y()}}async function A(){a++,m(),l();try{const n=await d(b,a);p(n.hits);const{height:o}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"});const e=Math.ceil(n.totalHits/L);a>=e?(s.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l()):g()}catch{s.error({title:"Error",message:"Something went wrong! while loading more images!",position:"topRight"})}finally{y()}}
//# sourceMappingURL=index.js.map
